# Generated by Django 4.2.15 on 2024-08-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ewiz_app', '0002_alter_jobopenings_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopenings',
            name='experience',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jobopenings',
            name='job_title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jobopenings',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jobopenings',
            name='salary',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jobopenings',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
